"""
This is a main_setup.py script generated by py2applet

Usage:
    python main_setup.py py2app
"""
import os
from setuptools import setup

PROJECT_PATH = "/Users/mr.cheng/GitSourceCodes/file_sharer-Desktop/"
PRODUCT_VERSION = "v0.1.0"


def generate_frontend_files():
    frontend_path = "static/mobile_frontend"
    src_path = PROJECT_PATH + frontend_path
    file_list = []
    for root, dirs, files in os.walk(src_path):
        rel_dir = os.path.relpath(root, src_path)
        target_dir = os.path.join(frontend_path, rel_dir)
        file_list.append((target_dir, [os.path.join(root, f) for f in files]))
    return file_list


APP = [PROJECT_PATH + "main.py"]
DATA_FILES = [
    PROJECT_PATH + "pyproject.toml",
    PROJECT_PATH + "file_sharing_backups.json",
    PROJECT_PATH + "static/themes/color_card.json",
    *generate_frontend_files(),
]
OPTIONS = {
    # Fix for #22
    # "argv_emulation": True,
    "includes": [
        "imp",
        "aiofiles",
        "aiohttp",
        "fastapi",
        "psutil",
        "pyftpdlib",
        "ftplib",
        "requests",
        "toml",
        "tomli",
        "yarl",
        "cryptography",
        "settings.development",
        "settings.production",
    ],
    "iconfile": PROJECT_PATH + "static/ui/icon.icns",
    "plist": {
        "CFBundleName": "FileSharer",
        "CFBundleDisplayName": "FileSharer",
        "CFBundleVersion": PRODUCT_VERSION,
        "CFBundleIdentifier": "FileSharer",
        "NSHumanReadableCopyright": "Copyright © 2023 zzmx-sudo.",
    },
    "packages": ["PyQt5", "chardet", "cchardet", "uvicorn", "anyio"],
    "excludes": ["setuptools"],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
    py_modules=[],
)
