[tool.black]
line-length = 88
target-version = [ "py39",]
include = "\\.py$"
extend-exclude = """
    /(static)/
"""
respect-gitignore = true

[file-sharer]
saveSystemLog = true
saveShareLog = true
logsPath = "/users/mr-cheng/GitSourceCodes/file_sharer-LAN/logs"
downloadPath = "/users/mr-cheng/GitSourceCodes/file_sharer-LAN/Download"