[file-sharer]
version = "0.4.1"
saveSystemLog = true
saveShareLog = true
logsPath = "F:\\GitSource\\file_sharer-Desktop\\logs"
downloadPath = "F:\\GitSource\\file_sharer-Desktop\\Download"
theme_color = "Default"
theme_opacity = 100
