# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtGui, QtWidgets

from . main_qrc import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 549)
        self.styleSheet = QtWidgets.QWidget(MainWindow)
        self.styleSheet.setStyleSheet("/* ///////////////////////////////////////////////////////////////////////////////\n"
"Global */\n"
"* {\n"
"    margin: 0;\n"
"    padding: 0;\n"
"    font-size: 14px;\n"
"    font-family: \"KaiTi\";\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"QWidget */\n"
"QWidget{\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"QCheckBox */\n"
"QCheckBox {\n"
"    spacing: 10px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 2px solid #409eff;\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 9px;\n"
"    background: rgb(236, 236, 236);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    background-color: #ffffff;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-image: url(:/icons/images/icon/check.png);\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"QTooltip */\n"
"QToolTip {\n"
"    color: #409eff;\n"
"    background-color: rgba(236, 236, 236, 180);\n"
"    border: 1px solid #409eff;\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 3px solid #409eff;\n"
"    text-align: left;\n"
"    padding-left: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"AppBg */\n"
"#AppBg {    \n"
"    background-color: #ffffff;\n"
"    border: 1px solid #409eff;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"QPushButton */\n"
"QPushButton {\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-radius: 5%;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Top Logo */\n"
"#topLogoInfo {\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Left Menu Box */\n"
"#leftMenuBox {\n"
"    background-color: rgb(222, 222, 222);\n"
"}\n"
"#leftMenuFrame {\n"
"    padding-bottom: 5px;\n"
"}\n"
"#leftBottomBox {\n"
"    padding: 0 5px;\n"
"}\n"
"#leftMenuBox .QPushButton:hover {\n"
"    background-color: #ffffff;\n"
"}\n"
"#leftMenuBox .QPushButton:pressed {\n"
"    background-color: #409eff;\n"
"}\n"
"#leftTopBox .QPushButton {\n"
"    border: none;\n"
"    border-radius: 0;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Extra Box */\n"
"#extraBox {\n"
"    background-color: rgb(236, 236, 236);\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Extra Top Box */\n"
"#extraTopBox {\n"
"    background-color: rgb(64, 158, 255);\n"
"    padding: 0 10px;\n"
"}\n"
"#extraTopBox .QLabel {\n"
"    color: #ffffff;\n"
"    font: 14px \"JetBrains Mono\";\n"
"}\n"
"#extraTopBox .QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"#extraTopBox .QPushButton:pressed {\n"
"    background-color: #ffffff;\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Extra Content Box */\n"
"#extraContentBox {\n"
"    margin: 10px 0;\n"
"}\n"
"#extraContentBox #saveShareBox, #saveSystemBox {\n"
"    padding-left: 15px;\n"
"}\n"
"#downloadPathBox, #logPathBox {\n"
"    padding: 10px;\n"
"}\n"
"#logPathLabel, #downloadPathLabel {\n"
"    margin-bottom: 5px;\n"
"}\n"
"#logPathEdit, #downloadPathEdit {\n"
"    border: 1px solid #409eff;\n"
"    border-radius: 3%;\n"
"    margin-right: 10px;\n"
"    background-color: rgb(236, 236, 236);\n"
"    font: 12px \"JetBrains Mono\";\n"
"}\n"
"#logPathButton, #downloadPathButton {\n"
"    border: 2px solid #409eff;\n"
"    border-radius: 5%;\n"
"}\n"
"#logPathButton:hover, #downloadPathButton:hover {\n"
"    background-color: #ffffff;\n"
"}\n"
"#logPathButton:pressed, #downloadPathButton:pressed {\n"
"    background-color: #409eff;\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Extra Bottom Box */\n"
"#extraBottomBox #saveSettingButton {\n"
"    background-color: rgb(42, 188, 255);\n"
"    color: #ffffff;\n"
"}\n"
"#extraBottomBox #saveSettingButton:hover {\n"
"    background-color: rgb(64, 158, 255);\n"
"}\n"
"#extraBottomBox #saveSettingButton:pressed {\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"#extraBottomBox #cancelSettingButton {\n"
"    background-color: rgb(217, 217, 217);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#extraBottomBox #cancelSettingButton:hover {\n"
"    background-color: rgb(184, 184, 184);\n"
"}\n"
"#extraBottomBox #cancelSettingButton:pressed {\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Content Box */\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Content Top Box */\n"
"#contentTopBox {\n"
"    background-color: rgb(236, 236, 236);\n"
"    padding: 0 10px 0 20px;\n"
"}\n"
"#contentTitleBox .QLabel {\n"
"    font: 14px \"JetBrains Mono\";\n"
"}\n"
"#contentTopBox .QPushButton:hover {\n"
"    background-color: #ffffff;\n"
"}\n"
"#contentTopBox .QPushButton:pressed {\n"
"    background-color: #409eff;\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Content Bottom Bar */\n"
"#contentBottomBar {\n"
"    background-color: rgb(236, 236, 236);\n"
"    color: rgb(97, 97, 97);\n"
"    padding: 0 10px;\n"
"}")
        self.styleSheet.setObjectName("styleSheet")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.styleSheet)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.AppBg = QtWidgets.QFrame(self.styleSheet)
        self.AppBg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AppBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AppBg.setObjectName("AppBg")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.AppBg)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftMenuBox = QtWidgets.QFrame(self.AppBg)
        self.leftMenuBox.setMinimumSize(QtCore.QSize(58, 0))
        self.leftMenuBox.setMaximumSize(QtCore.QSize(58, 16777215))
        self.leftMenuBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftMenuBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuBox.setLineWidth(1)
        self.leftMenuBox.setObjectName("leftMenuBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.leftMenuBox)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.topLogoInfo = QtWidgets.QFrame(self.leftMenuBox)
        self.topLogoInfo.setMinimumSize(QtCore.QSize(0, 45))
        self.topLogoInfo.setMaximumSize(QtCore.QSize(16777215, 45))
        self.topLogoInfo.setStyleSheet("background-image: url(:/icons/images/icon/share.png);")
        self.topLogoInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topLogoInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLogoInfo.setObjectName("topLogoInfo")
        self.verticalLayout_5.addWidget(self.topLogoInfo)
        self.leftMenuFrame = QtWidgets.QFrame(self.leftMenuBox)
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.leftTopBox = QtWidgets.QFrame(self.leftMenuFrame)
        self.leftTopBox.setMinimumSize(QtCore.QSize(0, 0))
        self.leftTopBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftTopBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftTopBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftTopBox.setObjectName("leftTopBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.leftTopBox)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.homeButton = QtWidgets.QPushButton(self.leftTopBox)
        self.homeButton.setMinimumSize(QtCore.QSize(0, 50))
        self.homeButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.homeButton.setStyleSheet("background-image: url(:/icons/images/icon/home.png);")
        self.homeButton.setText("")
        self.homeButton.setObjectName("homeButton")
        self.verticalLayout_8.addWidget(self.homeButton)
        self.serverButton = QtWidgets.QPushButton(self.leftTopBox)
        self.serverButton.setMinimumSize(QtCore.QSize(0, 50))
        self.serverButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.serverButton.setStyleSheet("background-image: url(:/icons/images/icon/server.png);")
        self.serverButton.setText("")
        self.serverButton.setObjectName("serverButton")
        self.verticalLayout_8.addWidget(self.serverButton)
        self.clientButton = QtWidgets.QPushButton(self.leftTopBox)
        self.clientButton.setMinimumSize(QtCore.QSize(0, 50))
        self.clientButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.clientButton.setStyleSheet("background-image: url(:/icons/images/icon/client.png);")
        self.clientButton.setText("")
        self.clientButton.setObjectName("clientButton")
        self.verticalLayout_8.addWidget(self.clientButton)
        self.downloadButton = QtWidgets.QPushButton(self.leftTopBox)
        self.downloadButton.setMinimumSize(QtCore.QSize(0, 50))
        self.downloadButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.downloadButton.setStyleSheet("background-image: url(:/icons/images/icon/download.png);")
        self.downloadButton.setText("")
        self.downloadButton.setObjectName("downloadButton")
        self.verticalLayout_8.addWidget(self.downloadButton)
        self.verticalLayout_4.addWidget(self.leftTopBox, 0, QtCore.Qt.AlignTop)
        self.leftBottomBox = QtWidgets.QFrame(self.leftMenuFrame)
        self.leftBottomBox.setMinimumSize(QtCore.QSize(0, 0))
        self.leftBottomBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftBottomBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftBottomBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBottomBox.setObjectName("leftBottomBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.leftBottomBox)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.settingButton = QtWidgets.QPushButton(self.leftBottomBox)
        self.settingButton.setMinimumSize(QtCore.QSize(0, 45))
        self.settingButton.setMaximumSize(QtCore.QSize(16777215, 45))
        self.settingButton.setStyleSheet("background-image: url(:/icons/images/icon/setting.png);")
        self.settingButton.setText("")
        self.settingButton.setObjectName("settingButton")
        self.verticalLayout_7.addWidget(self.settingButton)
        self.verticalLayout_4.addWidget(self.leftBottomBox, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_5.addWidget(self.leftMenuFrame)
        self.horizontalLayout_2.addWidget(self.leftMenuBox)
        self.extraBox = QtWidgets.QFrame(self.AppBg)
        self.extraBox.setMinimumSize(QtCore.QSize(0, 0))
        self.extraBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.extraBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.extraBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraBox.setLineWidth(1)
        self.extraBox.setObjectName("extraBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.extraBox)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.extraTopBox = QtWidgets.QFrame(self.extraBox)
        self.extraTopBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.extraTopBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.extraTopBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraTopBox.setObjectName("extraTopBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.extraTopBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.settingLabel = QtWidgets.QLabel(self.extraTopBox)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.settingLabel.setFont(font)
        self.settingLabel.setObjectName("settingLabel")
        self.horizontalLayout_5.addWidget(self.settingLabel)
        self.closeSettingButton = QtWidgets.QPushButton(self.extraTopBox)
        self.closeSettingButton.setMinimumSize(QtCore.QSize(28, 28))
        self.closeSettingButton.setMaximumSize(QtCore.QSize(28, 28))
        self.closeSettingButton.setStyleSheet("background-image: url(:/icons/images/icon/close-active.png);")
        self.closeSettingButton.setText("")
        self.closeSettingButton.setObjectName("closeSettingButton")
        self.horizontalLayout_5.addWidget(self.closeSettingButton)
        self.verticalLayout_3.addWidget(self.extraTopBox)
        self.extraContentBox = QtWidgets.QFrame(self.extraBox)
        self.extraContentBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.extraContentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraContentBox.setObjectName("extraContentBox")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.extraContentBox)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.saveSystemBox = QtWidgets.QFrame(self.extraContentBox)
        self.saveSystemBox.setMinimumSize(QtCore.QSize(0, 40))
        self.saveSystemBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.saveSystemBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saveSystemBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.saveSystemBox.setObjectName("saveSystemBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.saveSystemBox)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.saveSystemCheck = QtWidgets.QCheckBox(self.saveSystemBox)
        self.saveSystemCheck.setObjectName("saveSystemCheck")
        self.horizontalLayout_6.addWidget(self.saveSystemCheck)
        self.verticalLayout_15.addWidget(self.saveSystemBox)
        self.saveShareBox = QtWidgets.QFrame(self.extraContentBox)
        self.saveShareBox.setMinimumSize(QtCore.QSize(0, 40))
        self.saveShareBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.saveShareBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saveShareBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.saveShareBox.setObjectName("saveShareBox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.saveShareBox)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.saveSgareCheck = QtWidgets.QCheckBox(self.saveShareBox)
        self.saveSgareCheck.setObjectName("saveSgareCheck")
        self.horizontalLayout_7.addWidget(self.saveSgareCheck)
        self.verticalLayout_15.addWidget(self.saveShareBox)
        self.logPathBox = QtWidgets.QFrame(self.extraContentBox)
        self.logPathBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logPathBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logPathBox.setObjectName("logPathBox")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.logPathBox)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.logPathLabel = QtWidgets.QLabel(self.logPathBox)
        self.logPathLabel.setObjectName("logPathLabel")
        self.verticalLayout_13.addWidget(self.logPathLabel)
        self.logPathFrame = QtWidgets.QFrame(self.logPathBox)
        self.logPathFrame.setMinimumSize(QtCore.QSize(0, 30))
        self.logPathFrame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.logPathFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logPathFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logPathFrame.setObjectName("logPathFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.logPathFrame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.logPathEdit = QtWidgets.QLineEdit(self.logPathFrame)
        self.logPathEdit.setText("")
        self.logPathEdit.setObjectName("logPathEdit")
        self.horizontalLayout_8.addWidget(self.logPathEdit)
        self.logPathButton = QtWidgets.QPushButton(self.logPathFrame)
        self.logPathButton.setMinimumSize(QtCore.QSize(40, 20))
        self.logPathButton.setMaximumSize(QtCore.QSize(40, 20))
        self.logPathButton.setStyleSheet("background-image: url(:/icons/images/icon/folder.png);")
        self.logPathButton.setText("")
        self.logPathButton.setObjectName("logPathButton")
        self.horizontalLayout_8.addWidget(self.logPathButton)
        self.verticalLayout_13.addWidget(self.logPathFrame)
        self.verticalLayout_15.addWidget(self.logPathBox)
        self.downloadPathBox = QtWidgets.QFrame(self.extraContentBox)
        self.downloadPathBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.downloadPathBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.downloadPathBox.setObjectName("downloadPathBox")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.downloadPathBox)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.downloadPathLabel = QtWidgets.QLabel(self.downloadPathBox)
        self.downloadPathLabel.setObjectName("downloadPathLabel")
        self.verticalLayout_14.addWidget(self.downloadPathLabel)
        self.downloadPathFrame = QtWidgets.QFrame(self.downloadPathBox)
        self.downloadPathFrame.setMinimumSize(QtCore.QSize(0, 30))
        self.downloadPathFrame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.downloadPathFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.downloadPathFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.downloadPathFrame.setObjectName("downloadPathFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.downloadPathFrame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.downloadPathEdit = QtWidgets.QLineEdit(self.downloadPathFrame)
        self.downloadPathEdit.setObjectName("downloadPathEdit")
        self.horizontalLayout_9.addWidget(self.downloadPathEdit)
        self.downloadPathButton = QtWidgets.QPushButton(self.downloadPathFrame)
        self.downloadPathButton.setMinimumSize(QtCore.QSize(40, 20))
        self.downloadPathButton.setMaximumSize(QtCore.QSize(40, 20))
        self.downloadPathButton.setStyleSheet("background-image: url(:/icons/images/icon/folder.png);")
        self.downloadPathButton.setText("")
        self.downloadPathButton.setObjectName("downloadPathButton")
        self.horizontalLayout_9.addWidget(self.downloadPathButton)
        self.verticalLayout_14.addWidget(self.downloadPathFrame)
        self.verticalLayout_15.addWidget(self.downloadPathBox)
        self.verticalLayout_3.addWidget(self.extraContentBox, 0, QtCore.Qt.AlignTop)
        self.extraBottomBox = QtWidgets.QFrame(self.extraBox)
        self.extraBottomBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.extraBottomBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.extraBottomBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraBottomBox.setObjectName("extraBottomBox")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.extraBottomBox)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.saveSettingButton = QtWidgets.QPushButton(self.extraBottomBox)
        self.saveSettingButton.setMinimumSize(QtCore.QSize(120, 30))
        self.saveSettingButton.setMaximumSize(QtCore.QSize(120, 30))
        self.saveSettingButton.setObjectName("saveSettingButton")
        self.verticalLayout_12.addWidget(self.saveSettingButton)
        self.cancelSettingButton = QtWidgets.QPushButton(self.extraBottomBox)
        self.cancelSettingButton.setMinimumSize(QtCore.QSize(120, 30))
        self.cancelSettingButton.setMaximumSize(QtCore.QSize(120, 30))
        self.cancelSettingButton.setObjectName("cancelSettingButton")
        self.verticalLayout_12.addWidget(self.cancelSettingButton)
        self.verticalLayout_3.addWidget(self.extraBottomBox, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.extraBox)
        self.contentBox = QtWidgets.QFrame(self.AppBg)
        self.contentBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBox.setLineWidth(0)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentTopBox = QtWidgets.QFrame(self.contentBox)
        self.contentTopBox.setMaximumSize(QtCore.QSize(16777215, 45))
        self.contentTopBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentTopBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTopBox.setObjectName("contentTopBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentTopBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.contentTitleBox = QtWidgets.QFrame(self.contentTopBox)
        self.contentTitleBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentTitleBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTitleBox.setObjectName("contentTitleBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.contentTitleBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.contentTitleLabel = QtWidgets.QLabel(self.contentTitleBox)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.contentTitleLabel.setFont(font)
        self.contentTitleLabel.setObjectName("contentTitleLabel")
        self.verticalLayout_9.addWidget(self.contentTitleLabel)
        self.horizontalLayout.addWidget(self.contentTitleBox, 0, QtCore.Qt.AlignLeft)
        self.contentButtonBox = QtWidgets.QFrame(self.contentTopBox)
        self.contentButtonBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.contentButtonBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentButtonBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentButtonBox.setObjectName("contentButtonBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.contentButtonBox)
        self.horizontalLayout_3.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minimizeButton = QtWidgets.QPushButton(self.contentButtonBox)
        self.minimizeButton.setMinimumSize(QtCore.QSize(28, 28))
        self.minimizeButton.setMaximumSize(QtCore.QSize(28, 28))
        self.minimizeButton.setStyleSheet("background-image: url(:/icons/images/icon/minimize.png);")
        self.minimizeButton.setText("")
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout_3.addWidget(self.minimizeButton)
        self.maximizeRestoreButton = QtWidgets.QPushButton(self.contentButtonBox)
        self.maximizeRestoreButton.setMinimumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreButton.setMaximumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreButton.setStyleSheet("background-image: url(:/icons/images/icon/maximize.png);")
        self.maximizeRestoreButton.setText("")
        self.maximizeRestoreButton.setObjectName("maximizeRestoreButton")
        self.horizontalLayout_3.addWidget(self.maximizeRestoreButton)
        self.closeAppButton = QtWidgets.QPushButton(self.contentButtonBox)
        self.closeAppButton.setMinimumSize(QtCore.QSize(28, 28))
        self.closeAppButton.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppButton.setStyleSheet("background-image: url(:/icons/images/icon/close.png);")
        self.closeAppButton.setText("")
        self.closeAppButton.setObjectName("closeAppButton")
        self.horizontalLayout_3.addWidget(self.closeAppButton)
        self.horizontalLayout.addWidget(self.contentButtonBox, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.contentTopBox)
        self.contentBottomBox = QtWidgets.QFrame(self.contentBox)
        self.contentBottomBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentBottomBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBottomBox.setLineWidth(1)
        self.contentBottomBox.setObjectName("contentBottomBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.contentBottomBox)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.content = QtWidgets.QFrame(self.contentBottomBox)
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.verticalLayout.addWidget(self.content)
        self.contentBottomBar = QtWidgets.QFrame(self.contentBottomBox)
        self.contentBottomBar.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("KaiTi")
        font.setPointSize(-1)
        self.contentBottomBar.setFont(font)
        self.contentBottomBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentBottomBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBottomBar.setObjectName("contentBottomBar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.contentBottomBar)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.authorLabelBox = QtWidgets.QFrame(self.contentBottomBar)
        font = QtGui.QFont()
        font.setFamily("KaiTi")
        font.setPointSize(-1)
        self.authorLabelBox.setFont(font)
        self.authorLabelBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.authorLabelBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.authorLabelBox.setObjectName("authorLabelBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.authorLabelBox)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.authorLabel = QtWidgets.QLabel(self.authorLabelBox)
        font = QtGui.QFont()
        font.setFamily("KaiTi")
        font.setPointSize(-1)
        self.authorLabel.setFont(font)
        self.authorLabel.setObjectName("authorLabel")
        self.verticalLayout_10.addWidget(self.authorLabel, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_4.addWidget(self.authorLabelBox)
        self.versionLabelBox = QtWidgets.QFrame(self.contentBottomBar)
        self.versionLabelBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.versionLabelBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.versionLabelBox.setObjectName("versionLabelBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.versionLabelBox)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.versionLabel = QtWidgets.QLabel(self.versionLabelBox)
        self.versionLabel.setObjectName("versionLabel")
        self.verticalLayout_11.addWidget(self.versionLabel, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_4.addWidget(self.versionLabelBox)
        self.verticalLayout.addWidget(self.contentBottomBar)
        self.verticalLayout_2.addWidget(self.contentBottomBox)
        self.horizontalLayout_2.addWidget(self.contentBox)
        self.verticalLayout_6.addWidget(self.AppBg)
        MainWindow.setCentralWidget(self.styleSheet)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.settingLabel.setText(_translate("MainWindow", "Settings"))
        self.saveSystemCheck.setText(_translate("MainWindow", "保存系统日志"))
        self.saveSgareCheck.setText(_translate("MainWindow", "保存分享日志"))
        self.logPathLabel.setText(_translate("MainWindow", "日志路径："))
        self.downloadPathLabel.setText(_translate("MainWindow", "下载路径："))
        self.saveSettingButton.setText(_translate("MainWindow", "保存"))
        self.cancelSettingButton.setText(_translate("MainWindow", "取消"))
        self.contentTitleLabel.setText(_translate("MainWindow", "File Sharer - LAN file sharing helper."))
        self.authorLabel.setText(_translate("MainWindow", "By: 大宝天天见丶"))
        self.versionLabel.setText(_translate("MainWindow", "v0.0.1"))
