# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtGui, QtWidgets

from . main_qrc import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 580)
        self.styleSheet = QtWidgets.QWidget(MainWindow)
        self.styleSheet.setStyleSheet("/* ///////////////////////////////////////////////////////////////////////////////\n"
"Global */\n"
"* {\n"
"    margin: 0;\n"
"    padding: 0;\n"
"    font-size: 14px;\n"
"    font-family: \"KaiTi\";\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"QWidget */\n"
"QWidget{\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"QComboBox */\n"
"QComboBox {\n"
"    background-color: rgb(236, 236, 236);\n"
"    border-radius: 5%;\n"
"    border: 2px solid #409eff;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: #409eff;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #409eff;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    background-image: url(:/icons/images/icon/down.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"}\n"
"QComboBox::drop-down:hover {\n"
"    background-image: url(:/icons/images/icon/down-avtive.png);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(236, 236, 236);\n"
"    padding: 10px;\n"
"    selection-background-color: #409eff;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"QTableWidget {\n"
"    background-color: rgb(247, 247, 247);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(236, 236, 236);\n"
"    border-top: 2px solid #ffffff;\n"
"    border-bottom: 2px solid #409eff;\n"
"}\n"
"QTableWidget::item {\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(236, 236, 236);\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(126, 199, 255);\n"
"}\n"
"QTableWidget::horizontalHeader {\n"
"    background-color: rgb(247, 247, 247);\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: rgb(247, 247, 247);\n"
"    max-width: 100px;\n"
"    border: none;\n"
"    border-style: none;\n"
"}\n"
"QHeaderView::section:horizontal {\n"
"    border: 1px solid #409eff;\n"
"    background-color: rgb(247, 247, 247);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical {\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"QScrollBar */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(236, 236, 236);\n"
"    height: 8px;\n"
"    margin: 0 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(236, 236, 236);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #409eff;\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::handle:vertical {    \n"
"    background: #409eff;\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(100, 100, 100);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: rgb(100, 100, 100);\n"
"    height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(100, 100, 100);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(100, 100, 100);\n"
"    height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:vertical, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::add-page:horizontal, QScrollBar::sub-page:vertical, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"QCheckBox */\n"
"QCheckBox {\n"
"    spacing: 10px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 2px solid #409eff;\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 9px;\n"
"    background: rgb(236, 236, 236);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    background-color: #ffffff;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-image: url(:/icons/images/icon/check.png);\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"QTooltip */\n"
"QToolTip {\n"
"    color: #409eff;\n"
"    background-color: rgba(236, 236, 236, 180);\n"
"    border: 1px solid #409eff;\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 3px solid #409eff;\n"
"    text-align: left;\n"
"    padding-left: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"AppBg */\n"
"#AppBg {    \n"
"    background-color: #ffffff;\n"
"    border: 1px solid #409eff;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"QPushButton */\n"
"QPushButton {\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    border: 2px solid rgb(126, 199, 255);\n"
"    border-radius: 5%;\n"
"    background-color: rg(236, 236, 236)\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid #409eff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #409eff;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(200, 200, 200);\n"
"    border: none;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Top Logo */\n"
"#topLogoInfo {\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Left Menu Box */\n"
"#leftMenuBox {\n"
"    background-color: rgb(222, 222, 222);\n"
"}\n"
"#leftMenuFrame {\n"
"    padding-bottom: 5px;\n"
"}\n"
"#leftBottomBox {\n"
"    padding: 0 5px;\n"
"}\n"
"#leftMenuBox .QPushButton:hover {\n"
"    background-color: #ffffff;\n"
"}\n"
"#leftMenuBox .QPushButton:pressed {\n"
"    background-color: #409eff;\n"
"}\n"
"#leftTopBox .QPushButton {\n"
"    border: none;\n"
"    border-radius: 0;\n"
"}\n"
"#settingButton {\n"
"    border: none;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Extra Box */\n"
"#extraBox {\n"
"    background-color: rgb(236, 236, 236);\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Extra Top Box */\n"
"#extraTopBox {\n"
"    background-color: rgb(64, 158, 255);\n"
"    padding: 0 10px;\n"
"}\n"
"#extraTopBox .QLabel {\n"
"    color: #ffffff;\n"
"    font-size: 18px;\n"
"}\n"
"#extraTopBox .QPushButton {\n"
"    border: none;\n"
"}\n"
"#extraTopBox .QPushButton:hover {\n"
"    border: none;\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"#extraTopBox .QPushButton:pressed {\n"
"    background-color: #ffffff;\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Extra Content Box */\n"
"#extraContentBox {\n"
"    margin: 10px 0;\n"
"}\n"
"#extraContentBox #saveShareBox, #saveSystemBox {\n"
"    padding-left: 15px;\n"
"}\n"
"#downloadPathBox, #logPathBox {\n"
"    padding: 10px;\n"
"}\n"
"#extraContentBox .QLabel {\n"
"    margin-bottom: 5px;\n"
"}\n"
"#extraContentBox .QLineEdit {\n"
"    border: 1px solid #409eff;\n"
"    border-radius: 3%;\n"
"    margin-right: 10px;\n"
"    background-color: rgb(236, 236, 236);\n"
"    font: 12px \"JetBrains Mono\";\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Extra Bottom Box */\n"
"#extraBottomBox #saveSettingButton {\n"
"    border: none;\n"
"    background-color: rgb(42, 188, 255);\n"
"    color: #ffffff;\n"
"}\n"
"#extraBottomBox #saveSettingButton:hover {\n"
"    border: none;\n"
"    background-color: rgb(64, 158, 255);\n"
"}\n"
"#extraBottomBox #saveSettingButton:pressed {\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"#extraBottomBox #cancelSettingButton {\n"
"    border: none;\n"
"    background-color: rgb(217, 217, 217);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#extraBottomBox #cancelSettingButton:hover {\n"
"    border: none;\n"
"    background-color: rgb(184, 184, 184);\n"
"}\n"
"#extraBottomBox #cancelSettingButton:pressed {\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Content Box */\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Content Top Box */\n"
"#contentTopBox {\n"
"    background-color: rgb(236, 236, 236);\n"
"    padding: 0 10px 0 20px;\n"
"}\n"
"#contentTitleBox .QLabel {\n"
"    font: 14px \"JetBrains Mono\";\n"
"}\n"
"#contentTopBox .QPushButton {\n"
"    border: none;\n"
"}\n"
"#contentTopBox .QPushButton:hover {\n"
"    border: none;\n"
"    background-color: #ffffff;\n"
"}\n"
"#contentTopBox .QPushButton:pressed {\n"
"    border: none;\n"
"    background-color: #409eff;\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Content Bottom Box */\n"
"#contentBottomBox {\n"
"    background-color: rgb(246, 246, 246);\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Content stackedWidget Box */\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Content server Box */\n"
"#server {\n"
"    background-color: rgb(246, 246, 246);\n"
"}\n"
"#createShareButton {\n"
"    border: none;\n"
"    border-radius: 13%;\n"
"    background-color: rgb(42, 188, 255);\n"
"    color: #ffffff;\n"
"}\n"
"#createShareButton:hover {\n"
"    border: none;\n"
"    background-color: rgb(64, 158, 255);\n"
"}\n"
"#createShareButton:pressed {\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"#sharePathFrame .QLineEdit {\n"
"    border: 1px solid #409eff;\n"
"    border-radius: 5%;\n"
"    margin-right: 10px;\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Content client Box */\n"
"#clientParamFrame .QLineEdit {\n"
"    border: 1px solid #409eff;\n"
"    border-radius: 5%;\n"
"    padding-left: 10px;\n"
"}\n"
"#fileListFrame .QTableWidget::item:selected {\n"
"    background-color: rgb(247, 247, 247);\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////\n"
"Content Bottom Bar */\n"
"#contentBottomBar {\n"
"    background-color: rgb(236, 236, 236);\n"
"    color: rgb(97, 97, 97);\n"
"    padding: 0 10px;\n"
"}")
        self.styleSheet.setObjectName("styleSheet")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.styleSheet)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.AppBg = QtWidgets.QFrame(self.styleSheet)
        self.AppBg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AppBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AppBg.setObjectName("AppBg")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.AppBg)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftMenuBox = QtWidgets.QFrame(self.AppBg)
        self.leftMenuBox.setMinimumSize(QtCore.QSize(58, 0))
        self.leftMenuBox.setMaximumSize(QtCore.QSize(58, 16777215))
        self.leftMenuBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftMenuBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuBox.setLineWidth(1)
        self.leftMenuBox.setObjectName("leftMenuBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.leftMenuBox)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.topLogoInfo = QtWidgets.QFrame(self.leftMenuBox)
        self.topLogoInfo.setMinimumSize(QtCore.QSize(0, 45))
        self.topLogoInfo.setMaximumSize(QtCore.QSize(16777215, 45))
        self.topLogoInfo.setStyleSheet("background-image: url(:/icons/images/icon/share.png);")
        self.topLogoInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topLogoInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLogoInfo.setObjectName("topLogoInfo")
        self.verticalLayout_5.addWidget(self.topLogoInfo)
        self.leftMenuFrame = QtWidgets.QFrame(self.leftMenuBox)
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.leftTopBox = QtWidgets.QFrame(self.leftMenuFrame)
        self.leftTopBox.setMinimumSize(QtCore.QSize(0, 0))
        self.leftTopBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftTopBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftTopBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftTopBox.setObjectName("leftTopBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.leftTopBox)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.homeButton = QtWidgets.QPushButton(self.leftTopBox)
        self.homeButton.setMinimumSize(QtCore.QSize(0, 50))
        self.homeButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.homeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeButton.setStyleSheet("background-image: url(:/icons/images/icon/home.png);")
        self.homeButton.setText("")
        self.homeButton.setObjectName("homeButton")
        self.verticalLayout_8.addWidget(self.homeButton)
        self.serverButton = QtWidgets.QPushButton(self.leftTopBox)
        self.serverButton.setMinimumSize(QtCore.QSize(0, 50))
        self.serverButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.serverButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.serverButton.setStyleSheet("background-image: url(:/icons/images/icon/server.png);")
        self.serverButton.setText("")
        self.serverButton.setObjectName("serverButton")
        self.verticalLayout_8.addWidget(self.serverButton)
        self.clientButton = QtWidgets.QPushButton(self.leftTopBox)
        self.clientButton.setMinimumSize(QtCore.QSize(0, 50))
        self.clientButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.clientButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clientButton.setStyleSheet("background-image: url(:/icons/images/icon/client.png);")
        self.clientButton.setText("")
        self.clientButton.setObjectName("clientButton")
        self.verticalLayout_8.addWidget(self.clientButton)
        self.downloadButton = QtWidgets.QPushButton(self.leftTopBox)
        self.downloadButton.setMinimumSize(QtCore.QSize(0, 50))
        self.downloadButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.downloadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.downloadButton.setStyleSheet("background-image: url(:/icons/images/icon/download.png);")
        self.downloadButton.setText("")
        self.downloadButton.setObjectName("downloadButton")
        self.verticalLayout_8.addWidget(self.downloadButton)
        self.verticalLayout_4.addWidget(self.leftTopBox, 0, QtCore.Qt.AlignTop)
        self.leftBottomBox = QtWidgets.QFrame(self.leftMenuFrame)
        self.leftBottomBox.setMinimumSize(QtCore.QSize(0, 0))
        self.leftBottomBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftBottomBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftBottomBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBottomBox.setObjectName("leftBottomBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.leftBottomBox)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.settingButton = QtWidgets.QPushButton(self.leftBottomBox)
        self.settingButton.setMinimumSize(QtCore.QSize(0, 45))
        self.settingButton.setMaximumSize(QtCore.QSize(16777215, 45))
        self.settingButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingButton.setStyleSheet("background-image: url(:/icons/images/icon/setting.png);")
        self.settingButton.setText("")
        self.settingButton.setObjectName("settingButton")
        self.verticalLayout_7.addWidget(self.settingButton)
        self.verticalLayout_4.addWidget(self.leftBottomBox, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_5.addWidget(self.leftMenuFrame)
        self.horizontalLayout_2.addWidget(self.leftMenuBox)
        self.extraBox = QtWidgets.QFrame(self.AppBg)
        self.extraBox.setMinimumSize(QtCore.QSize(0, 0))
        self.extraBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.extraBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.extraBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraBox.setLineWidth(1)
        self.extraBox.setObjectName("extraBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.extraBox)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.extraTopBox = QtWidgets.QFrame(self.extraBox)
        self.extraTopBox.setMaximumSize(QtCore.QSize(16777215, 45))
        self.extraTopBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.extraTopBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraTopBox.setObjectName("extraTopBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.extraTopBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.settingLabel = QtWidgets.QLabel(self.extraTopBox)
        font = QtGui.QFont()
        font.setFamily("KaiTi")
        self.settingLabel.setFont(font)
        self.settingLabel.setObjectName("settingLabel")
        self.horizontalLayout_5.addWidget(self.settingLabel)
        self.closeSettingButton = QtWidgets.QPushButton(self.extraTopBox)
        self.closeSettingButton.setMinimumSize(QtCore.QSize(28, 28))
        self.closeSettingButton.setMaximumSize(QtCore.QSize(28, 28))
        self.closeSettingButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeSettingButton.setStyleSheet("background-image: url(:/icons/images/icon/close-active.png);")
        self.closeSettingButton.setText("")
        self.closeSettingButton.setObjectName("closeSettingButton")
        self.horizontalLayout_5.addWidget(self.closeSettingButton)
        self.verticalLayout_3.addWidget(self.extraTopBox)
        self.extraContentBox = QtWidgets.QFrame(self.extraBox)
        self.extraContentBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.extraContentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraContentBox.setObjectName("extraContentBox")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.extraContentBox)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.saveSystemBox = QtWidgets.QFrame(self.extraContentBox)
        self.saveSystemBox.setMinimumSize(QtCore.QSize(0, 40))
        self.saveSystemBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.saveSystemBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saveSystemBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.saveSystemBox.setObjectName("saveSystemBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.saveSystemBox)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.saveSystemCheck = QtWidgets.QCheckBox(self.saveSystemBox)
        self.saveSystemCheck.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveSystemCheck.setObjectName("saveSystemCheck")
        self.horizontalLayout_6.addWidget(self.saveSystemCheck)
        self.verticalLayout_15.addWidget(self.saveSystemBox)
        self.saveShareBox = QtWidgets.QFrame(self.extraContentBox)
        self.saveShareBox.setMinimumSize(QtCore.QSize(0, 40))
        self.saveShareBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.saveShareBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saveShareBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.saveShareBox.setObjectName("saveShareBox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.saveShareBox)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.saveShareCheck = QtWidgets.QCheckBox(self.saveShareBox)
        self.saveShareCheck.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveShareCheck.setObjectName("saveShareCheck")
        self.horizontalLayout_7.addWidget(self.saveShareCheck)
        self.verticalLayout_15.addWidget(self.saveShareBox)
        self.logPathBox = QtWidgets.QFrame(self.extraContentBox)
        self.logPathBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logPathBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logPathBox.setObjectName("logPathBox")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.logPathBox)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.logPathLabel = QtWidgets.QLabel(self.logPathBox)
        self.logPathLabel.setObjectName("logPathLabel")
        self.verticalLayout_13.addWidget(self.logPathLabel)
        self.logPathFrame = QtWidgets.QFrame(self.logPathBox)
        self.logPathFrame.setMinimumSize(QtCore.QSize(0, 30))
        self.logPathFrame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.logPathFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logPathFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logPathFrame.setObjectName("logPathFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.logPathFrame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.logPathEdit = QtWidgets.QLineEdit(self.logPathFrame)
        self.logPathEdit.setText("")
        self.logPathEdit.setObjectName("logPathEdit")
        self.horizontalLayout_8.addWidget(self.logPathEdit)
        self.logPathButton = QtWidgets.QPushButton(self.logPathFrame)
        self.logPathButton.setMinimumSize(QtCore.QSize(40, 20))
        self.logPathButton.setMaximumSize(QtCore.QSize(40, 20))
        self.logPathButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logPathButton.setStyleSheet("background-image: url(:/icons/images/icon/folder.png);")
        self.logPathButton.setText("")
        self.logPathButton.setObjectName("logPathButton")
        self.horizontalLayout_8.addWidget(self.logPathButton)
        self.verticalLayout_13.addWidget(self.logPathFrame)
        self.verticalLayout_15.addWidget(self.logPathBox)
        self.downloadPathBox = QtWidgets.QFrame(self.extraContentBox)
        self.downloadPathBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.downloadPathBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.downloadPathBox.setObjectName("downloadPathBox")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.downloadPathBox)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.downloadPathLabel = QtWidgets.QLabel(self.downloadPathBox)
        self.downloadPathLabel.setObjectName("downloadPathLabel")
        self.verticalLayout_14.addWidget(self.downloadPathLabel)
        self.downloadPathFrame = QtWidgets.QFrame(self.downloadPathBox)
        self.downloadPathFrame.setMinimumSize(QtCore.QSize(0, 30))
        self.downloadPathFrame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.downloadPathFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.downloadPathFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.downloadPathFrame.setObjectName("downloadPathFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.downloadPathFrame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.downloadPathEdit = QtWidgets.QLineEdit(self.downloadPathFrame)
        self.downloadPathEdit.setObjectName("downloadPathEdit")
        self.horizontalLayout_9.addWidget(self.downloadPathEdit)
        self.downloadPathButton = QtWidgets.QPushButton(self.downloadPathFrame)
        self.downloadPathButton.setMinimumSize(QtCore.QSize(40, 20))
        self.downloadPathButton.setMaximumSize(QtCore.QSize(40, 20))
        self.downloadPathButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.downloadPathButton.setStyleSheet("background-image: url(:/icons/images/icon/folder.png);")
        self.downloadPathButton.setText("")
        self.downloadPathButton.setObjectName("downloadPathButton")
        self.horizontalLayout_9.addWidget(self.downloadPathButton)
        self.verticalLayout_14.addWidget(self.downloadPathFrame)
        self.verticalLayout_15.addWidget(self.downloadPathBox)
        self.outsideLinkFrame = QtWidgets.QFrame(self.extraContentBox)
        self.outsideLinkFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outsideLinkFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outsideLinkFrame.setObjectName("outsideLinkFrame")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.outsideLinkFrame)
        self.verticalLayout_17.setContentsMargins(10, 10, 0, 10)
        self.verticalLayout_17.setSpacing(5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.shareProjectButton = QtWidgets.QPushButton(self.outsideLinkFrame)
        self.shareProjectButton.setMinimumSize(QtCore.QSize(100, 26))
        self.shareProjectButton.setMaximumSize(QtCore.QSize(100, 26))
        self.shareProjectButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icon/share.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shareProjectButton.setIcon(icon)
        self.shareProjectButton.setObjectName("shareProjectButton")
        self.verticalLayout_17.addWidget(self.shareProjectButton)
        self.browseProjectButton = QtWidgets.QPushButton(self.outsideLinkFrame)
        self.browseProjectButton.setMinimumSize(QtCore.QSize(100, 26))
        self.browseProjectButton.setMaximumSize(QtCore.QSize(100, 26))
        self.browseProjectButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icon/browse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browseProjectButton.setIcon(icon1)
        self.browseProjectButton.setObjectName("browseProjectButton")
        self.verticalLayout_17.addWidget(self.browseProjectButton)
        self.verticalLayout_15.addWidget(self.outsideLinkFrame)
        self.verticalLayout_3.addWidget(self.extraContentBox, 0, QtCore.Qt.AlignTop)
        self.extraBottomBox = QtWidgets.QFrame(self.extraBox)
        self.extraBottomBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.extraBottomBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.extraBottomBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraBottomBox.setObjectName("extraBottomBox")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.extraBottomBox)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.saveSettingButton = QtWidgets.QPushButton(self.extraBottomBox)
        self.saveSettingButton.setMinimumSize(QtCore.QSize(120, 30))
        self.saveSettingButton.setMaximumSize(QtCore.QSize(120, 30))
        self.saveSettingButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveSettingButton.setObjectName("saveSettingButton")
        self.verticalLayout_12.addWidget(self.saveSettingButton)
        self.cancelSettingButton = QtWidgets.QPushButton(self.extraBottomBox)
        self.cancelSettingButton.setMinimumSize(QtCore.QSize(120, 30))
        self.cancelSettingButton.setMaximumSize(QtCore.QSize(120, 30))
        self.cancelSettingButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelSettingButton.setObjectName("cancelSettingButton")
        self.verticalLayout_12.addWidget(self.cancelSettingButton)
        self.verticalLayout_3.addWidget(self.extraBottomBox, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.extraBox)
        self.contentBox = QtWidgets.QFrame(self.AppBg)
        self.contentBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBox.setLineWidth(0)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentTopBox = QtWidgets.QFrame(self.contentBox)
        self.contentTopBox.setMinimumSize(QtCore.QSize(0, 45))
        self.contentTopBox.setMaximumSize(QtCore.QSize(16777215, 45))
        self.contentTopBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentTopBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTopBox.setObjectName("contentTopBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentTopBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.contentTitleBox = QtWidgets.QFrame(self.contentTopBox)
        self.contentTitleBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentTitleBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTitleBox.setObjectName("contentTitleBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.contentTitleBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.contentTitleLabel = QtWidgets.QLabel(self.contentTitleBox)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.contentTitleLabel.setFont(font)
        self.contentTitleLabel.setObjectName("contentTitleLabel")
        self.verticalLayout_9.addWidget(self.contentTitleLabel)
        self.horizontalLayout.addWidget(self.contentTitleBox, 0, QtCore.Qt.AlignLeft)
        self.contentButtonBox = QtWidgets.QFrame(self.contentTopBox)
        self.contentButtonBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.contentButtonBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentButtonBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentButtonBox.setObjectName("contentButtonBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.contentButtonBox)
        self.horizontalLayout_3.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minimizeButton = QtWidgets.QPushButton(self.contentButtonBox)
        self.minimizeButton.setMinimumSize(QtCore.QSize(28, 28))
        self.minimizeButton.setMaximumSize(QtCore.QSize(28, 28))
        self.minimizeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeButton.setStyleSheet("background-image: url(:/icons/images/icon/minimize.png);")
        self.minimizeButton.setText("")
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout_3.addWidget(self.minimizeButton)
        self.maximizeRestoreButton = QtWidgets.QPushButton(self.contentButtonBox)
        self.maximizeRestoreButton.setMinimumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreButton.setMaximumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maximizeRestoreButton.setStyleSheet("background-image: url(:/icons/images/icon/maximize.png);")
        self.maximizeRestoreButton.setText("")
        self.maximizeRestoreButton.setObjectName("maximizeRestoreButton")
        self.horizontalLayout_3.addWidget(self.maximizeRestoreButton)
        self.closeAppButton = QtWidgets.QPushButton(self.contentButtonBox)
        self.closeAppButton.setMinimumSize(QtCore.QSize(28, 28))
        self.closeAppButton.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeAppButton.setStyleSheet("background-image: url(:/icons/images/icon/close.png);")
        self.closeAppButton.setText("")
        self.closeAppButton.setObjectName("closeAppButton")
        self.horizontalLayout_3.addWidget(self.closeAppButton)
        self.horizontalLayout.addWidget(self.contentButtonBox, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.contentTopBox)
        self.contentBottomBox = QtWidgets.QFrame(self.contentBox)
        self.contentBottomBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentBottomBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBottomBox.setLineWidth(1)
        self.contentBottomBox.setObjectName("contentBottomBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.contentBottomBox)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.content = QtWidgets.QFrame(self.contentBottomBox)
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.stackedWidget.addWidget(self.home)
        self.server = QtWidgets.QWidget()
        self.server.setObjectName("server")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.server)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.createShareParamFrame = QtWidgets.QFrame(self.server)
        self.createShareParamFrame.setMinimumSize(QtCore.QSize(0, 60))
        self.createShareParamFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.createShareParamFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.createShareParamFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.createShareParamFrame.setObjectName("createShareParamFrame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.createShareParamFrame)
        self.horizontalLayout_14.setContentsMargins(20, 5, 20, 5)
        self.horizontalLayout_14.setSpacing(20)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.shareTypeFrame = QtWidgets.QFrame(self.createShareParamFrame)
        self.shareTypeFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.shareTypeFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.shareTypeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shareTypeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.shareTypeFrame.setObjectName("shareTypeFrame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.shareTypeFrame)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.shareTypeLabel = QtWidgets.QLabel(self.shareTypeFrame)
        self.shareTypeLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.shareTypeLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.shareTypeLabel.setObjectName("shareTypeLabel")
        self.horizontalLayout_13.addWidget(self.shareTypeLabel)
        self.shareTypeCombo = QtWidgets.QComboBox(self.shareTypeFrame)
        self.shareTypeCombo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.shareTypeCombo.setObjectName("shareTypeCombo")
        self.shareTypeCombo.addItem("")
        self.shareTypeCombo.addItem("")
        self.horizontalLayout_13.addWidget(self.shareTypeCombo)
        self.horizontalLayout_14.addWidget(self.shareTypeFrame)
        self.sharePathFrame = QtWidgets.QFrame(self.createShareParamFrame)
        self.sharePathFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.sharePathFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sharePathFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sharePathFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sharePathFrame.setObjectName("sharePathFrame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.sharePathFrame)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.sharePathLabel = QtWidgets.QLabel(self.sharePathFrame)
        self.sharePathLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.sharePathLabel.setObjectName("sharePathLabel")
        self.horizontalLayout_12.addWidget(self.sharePathLabel)
        self.sharePathEdit = QtWidgets.QLineEdit(self.sharePathFrame)
        self.sharePathEdit.setMinimumSize(QtCore.QSize(152, 30))
        self.sharePathEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sharePathEdit.setObjectName("sharePathEdit")
        self.horizontalLayout_12.addWidget(self.sharePathEdit)
        self.sharePathButton = QtWidgets.QPushButton(self.sharePathFrame)
        self.sharePathButton.setMinimumSize(QtCore.QSize(60, 30))
        self.sharePathButton.setMaximumSize(QtCore.QSize(60, 30))
        self.sharePathButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sharePathButton.setStyleSheet("background-image: url(:/icons/images/icon/folder.png);")
        self.sharePathButton.setText("")
        self.sharePathButton.setObjectName("sharePathButton")
        self.horizontalLayout_12.addWidget(self.sharePathButton)
        self.horizontalLayout_14.addWidget(self.sharePathFrame)
        self.shareFileFrame = QtWidgets.QFrame(self.createShareParamFrame)
        self.shareFileFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.shareFileFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shareFileFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.shareFileFrame.setObjectName("shareFileFrame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.shareFileFrame)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.shareFileLbael = QtWidgets.QLabel(self.shareFileFrame)
        self.shareFileLbael.setMinimumSize(QtCore.QSize(120, 0))
        self.shareFileLbael.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.shareFileLbael.setObjectName("shareFileLbael")
        self.horizontalLayout_11.addWidget(self.shareFileLbael)
        self.shareFileCombo = QtWidgets.QComboBox(self.shareFileFrame)
        self.shareFileCombo.setMinimumSize(QtCore.QSize(180, 0))
        self.shareFileCombo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.shareFileCombo.setObjectName("shareFileCombo")
        self.horizontalLayout_11.addWidget(self.shareFileCombo)
        self.horizontalLayout_14.addWidget(self.shareFileFrame)
        self.verticalLayout_16.addWidget(self.createShareParamFrame)
        self.createShareButtonFrame = QtWidgets.QFrame(self.server)
        self.createShareButtonFrame.setMinimumSize(QtCore.QSize(0, 40))
        self.createShareButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.createShareButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.createShareButtonFrame.setObjectName("createShareButtonFrame")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.createShareButtonFrame)
        self.verticalLayout_18.setContentsMargins(20, 5, 20, 10)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.createShareButton = QtWidgets.QPushButton(self.createShareButtonFrame)
        self.createShareButton.setMinimumSize(QtCore.QSize(0, 26))
        self.createShareButton.setMaximumSize(QtCore.QSize(16777215, 26))
        self.createShareButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.createShareButton.setObjectName("createShareButton")
        self.verticalLayout_18.addWidget(self.createShareButton)
        self.verticalLayout_16.addWidget(self.createShareButtonFrame)
        self.shareListFrame = QtWidgets.QFrame(self.server)
        self.shareListFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.shareListFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shareListFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.shareListFrame.setObjectName("shareListFrame")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.shareListFrame)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.shareListTable = QtWidgets.QTableWidget(self.shareListFrame)
        self.shareListTable.setMinimumSize(QtCore.QSize(0, 0))
        self.shareListTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.shareListTable.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.shareListTable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.shareListTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.shareListTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.shareListTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.shareListTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.shareListTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.shareListTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.shareListTable.setObjectName("shareListTable")
        self.shareListTable.setColumnCount(6)
        self.shareListTable.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareListTable.setItem(0, 4, item)
        self.shareListTable.horizontalHeader().setVisible(True)
        self.shareListTable.horizontalHeader().setCascadingSectionResizes(False)
        self.shareListTable.horizontalHeader().setDefaultSectionSize(150)
        self.shareListTable.horizontalHeader().setHighlightSections(True)
        self.shareListTable.horizontalHeader().setMinimumSectionSize(50)
        self.shareListTable.horizontalHeader().setSortIndicatorShown(True)
        self.shareListTable.horizontalHeader().setStretchLastSection(True)
        self.shareListTable.verticalHeader().setVisible(False)
        self.shareListTable.verticalHeader().setCascadingSectionResizes(False)
        self.shareListTable.verticalHeader().setDefaultSectionSize(30)
        self.shareListTable.verticalHeader().setMinimumSectionSize(25)
        self.shareListTable.verticalHeader().setSortIndicatorShown(False)
        self.shareListTable.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_15.addWidget(self.shareListTable)
        self.verticalLayout_16.addWidget(self.shareListFrame)
        self.stackedWidget.addWidget(self.server)
        self.client = QtWidgets.QWidget()
        self.client.setObjectName("client")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.client)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.clientFrame = QtWidgets.QFrame(self.client)
        self.clientFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clientFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clientFrame.setObjectName("clientFrame")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.clientFrame)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.clientParamFrame = QtWidgets.QFrame(self.clientFrame)
        self.clientParamFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.clientParamFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.clientParamFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clientParamFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clientParamFrame.setObjectName("clientParamFrame")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.clientParamFrame)
        self.horizontalLayout_16.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_16.setSpacing(10)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.shareLinkLabel = QtWidgets.QLabel(self.clientParamFrame)
        self.shareLinkLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.shareLinkLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.shareLinkLabel.setObjectName("shareLinkLabel")
        self.horizontalLayout_16.addWidget(self.shareLinkLabel)
        self.shareLinkEdit = QtWidgets.QLineEdit(self.clientParamFrame)
        self.shareLinkEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.shareLinkEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.shareLinkEdit.setObjectName("shareLinkEdit")
        self.horizontalLayout_16.addWidget(self.shareLinkEdit)
        self.shareLinkButton = QtWidgets.QPushButton(self.clientParamFrame)
        self.shareLinkButton.setMinimumSize(QtCore.QSize(80, 30))
        self.shareLinkButton.setMaximumSize(QtCore.QSize(80, 30))
        self.shareLinkButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.shareLinkButton.setObjectName("shareLinkButton")
        self.horizontalLayout_16.addWidget(self.shareLinkButton)
        self.verticalLayout_20.addWidget(self.clientParamFrame)
        self.fileListFrame = QtWidgets.QFrame(self.clientFrame)
        self.fileListFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fileListFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fileListFrame.setObjectName("fileListFrame")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.fileListFrame)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.backupButtonFrame = QtWidgets.QFrame(self.fileListFrame)
        self.backupButtonFrame.setMinimumSize(QtCore.QSize(0, 30))
        self.backupButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.backupButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backupButtonFrame.setObjectName("backupButtonFrame")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.backupButtonFrame)
        self.horizontalLayout_17.setContentsMargins(10, 20, 10, 0)
        self.horizontalLayout_17.setSpacing(10)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.backupButton = QtWidgets.QPushButton(self.backupButtonFrame)
        self.backupButton.setMinimumSize(QtCore.QSize(130, 30))
        self.backupButton.setMaximumSize(QtCore.QSize(130, 30))
        self.backupButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icon/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backupButton.setIcon(icon2)
        self.backupButton.setIconSize(QtCore.QSize(16, 16))
        self.backupButton.setObjectName("backupButton")
        self.horizontalLayout_17.addWidget(self.backupButton, 0, QtCore.Qt.AlignLeft)
        self.downloadDirButton = QtWidgets.QPushButton(self.backupButtonFrame)
        self.downloadDirButton.setMinimumSize(QtCore.QSize(150, 30))
        self.downloadDirButton.setMaximumSize(QtCore.QSize(150, 30))
        self.downloadDirButton.setObjectName("downloadDirButton")
        self.horizontalLayout_17.addWidget(self.downloadDirButton, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_19.addWidget(self.backupButtonFrame, 0, QtCore.Qt.AlignLeft)
        self.fileListTable = QtWidgets.QTableWidget(self.fileListFrame)
        self.fileListTable.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fileListTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.fileListTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.fileListTable.setObjectName("fileListTable")
        self.fileListTable.setColumnCount(1)
        self.fileListTable.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.fileListTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fileListTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fileListTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fileListTable.setHorizontalHeaderItem(0, item)
        self.fileListTable.horizontalHeader().setVisible(True)
        self.fileListTable.horizontalHeader().setCascadingSectionResizes(False)
        self.fileListTable.horizontalHeader().setDefaultSectionSize(215)
        self.fileListTable.horizontalHeader().setMinimumSectionSize(50)
        self.fileListTable.horizontalHeader().setSortIndicatorShown(True)
        self.fileListTable.horizontalHeader().setStretchLastSection(True)
        self.fileListTable.verticalHeader().setVisible(False)
        self.fileListTable.verticalHeader().setCascadingSectionResizes(False)
        self.fileListTable.verticalHeader().setMinimumSectionSize(25)
        self.verticalLayout_19.addWidget(self.fileListTable)
        self.verticalLayout_20.addWidget(self.fileListFrame)
        self.verticalLayout_21.addWidget(self.clientFrame)
        self.stackedWidget.addWidget(self.client)
        self.download = QtWidgets.QWidget()
        self.download.setObjectName("download")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.download)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.downloadButtonFrame = QtWidgets.QFrame(self.download)
        self.downloadButtonFrame.setMinimumSize(QtCore.QSize(0, 40))
        self.downloadButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.downloadButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.downloadButtonFrame.setObjectName("downloadButtonFrame")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.downloadButtonFrame)
        self.horizontalLayout_18.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.removeDownloadsButton = QtWidgets.QPushButton(self.downloadButtonFrame)
        self.removeDownloadsButton.setMinimumSize(QtCore.QSize(120, 30))
        self.removeDownloadsButton.setMaximumSize(QtCore.QSize(120, 30))
        self.removeDownloadsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.removeDownloadsButton.setObjectName("removeDownloadsButton")
        self.horizontalLayout_18.addWidget(self.removeDownloadsButton, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_23.addWidget(self.downloadButtonFrame, 0, QtCore.Qt.AlignLeft)
        self.downloadListFrame = QtWidgets.QFrame(self.download)
        self.downloadListFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.downloadListFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.downloadListFrame.setObjectName("downloadListFrame")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.downloadListFrame)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.downloadListTable = QtWidgets.QTableWidget(self.downloadListFrame)
        self.downloadListTable.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.downloadListTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.downloadListTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.downloadListTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.downloadListTable.setObjectName("downloadListTable")
        self.downloadListTable.setColumnCount(2)
        self.downloadListTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.downloadListTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.downloadListTable.setHorizontalHeaderItem(1, item)
        self.downloadListTable.horizontalHeader().setVisible(True)
        self.downloadListTable.horizontalHeader().setDefaultSectionSize(240)
        self.downloadListTable.horizontalHeader().setMinimumSectionSize(50)
        self.downloadListTable.horizontalHeader().setSortIndicatorShown(True)
        self.downloadListTable.horizontalHeader().setStretchLastSection(True)
        self.downloadListTable.verticalHeader().setVisible(False)
        self.downloadListTable.verticalHeader().setMinimumSectionSize(25)
        self.verticalLayout_22.addWidget(self.downloadListTable)
        self.verticalLayout_23.addWidget(self.downloadListFrame)
        self.stackedWidget.addWidget(self.download)
        self.horizontalLayout_10.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.content)
        self.contentBottomBar = QtWidgets.QFrame(self.contentBottomBox)
        self.contentBottomBar.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("KaiTi")
        self.contentBottomBar.setFont(font)
        self.contentBottomBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentBottomBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBottomBar.setObjectName("contentBottomBar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.contentBottomBar)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.authorLabelBox = QtWidgets.QFrame(self.contentBottomBar)
        font = QtGui.QFont()
        font.setFamily("KaiTi")
        self.authorLabelBox.setFont(font)
        self.authorLabelBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.authorLabelBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.authorLabelBox.setObjectName("authorLabelBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.authorLabelBox)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.authorLabel = QtWidgets.QLabel(self.authorLabelBox)
        font = QtGui.QFont()
        font.setFamily("KaiTi")
        self.authorLabel.setFont(font)
        self.authorLabel.setObjectName("authorLabel")
        self.verticalLayout_10.addWidget(self.authorLabel, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_4.addWidget(self.authorLabelBox)
        self.versionLabelBox = QtWidgets.QFrame(self.contentBottomBar)
        self.versionLabelBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.versionLabelBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.versionLabelBox.setObjectName("versionLabelBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.versionLabelBox)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.versionLabel = QtWidgets.QLabel(self.versionLabelBox)
        self.versionLabel.setObjectName("versionLabel")
        self.verticalLayout_11.addWidget(self.versionLabel, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_4.addWidget(self.versionLabelBox)
        self.verticalLayout.addWidget(self.contentBottomBar)
        self.verticalLayout_2.addWidget(self.contentBottomBox)
        self.horizontalLayout_2.addWidget(self.contentBox)
        self.verticalLayout_6.addWidget(self.AppBg)
        MainWindow.setCentralWidget(self.styleSheet)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.homeButton.setToolTip(_translate("MainWindow", "首页"))
        self.serverButton.setToolTip(_translate("MainWindow", "服务端"))
        self.clientButton.setToolTip(_translate("MainWindow", "客户端"))
        self.downloadButton.setToolTip(_translate("MainWindow", "下载记录"))
        self.settingButton.setToolTip(_translate("MainWindow", "打开/关闭设置窗口"))
        self.settingLabel.setText(_translate("MainWindow", "设置"))
        self.closeSettingButton.setToolTip(_translate("MainWindow", "关闭设置窗口"))
        self.saveSystemCheck.setToolTip(_translate("MainWindow", "勾选保存系统日志"))
        self.saveSystemCheck.setText(_translate("MainWindow", "保存系统日志"))
        self.saveShareCheck.setToolTip(_translate("MainWindow", "勾选保存分享日志"))
        self.saveShareCheck.setText(_translate("MainWindow", "保存分享日志"))
        self.logPathLabel.setText(_translate("MainWindow", "日志路径："))
        self.logPathButton.setToolTip(_translate("MainWindow", "打开资源管理器选择路径"))
        self.downloadPathLabel.setText(_translate("MainWindow", "下载路径："))
        self.downloadPathButton.setToolTip(_translate("MainWindow", "打开资源管理器选择路径"))
        self.shareProjectButton.setText(_translate("MainWindow", "分享软件"))
        self.browseProjectButton.setText(_translate("MainWindow", "打开项目"))
        self.saveSettingButton.setToolTip(_translate("MainWindow", "保存配置"))
        self.saveSettingButton.setText(_translate("MainWindow", "保存"))
        self.cancelSettingButton.setToolTip(_translate("MainWindow", "撤回配置"))
        self.cancelSettingButton.setText(_translate("MainWindow", "撤回"))
        self.contentTitleLabel.setText(_translate("MainWindow", "File Sharer - LAN file sharing helper."))
        self.minimizeButton.setToolTip(_translate("MainWindow", "最小化窗口"))
        self.maximizeRestoreButton.setToolTip(_translate("MainWindow", "窗口全屏"))
        self.closeAppButton.setToolTip(_translate("MainWindow", "关闭应用"))
        self.shareTypeLabel.setText(_translate("MainWindow", "分享类型："))
        self.shareTypeCombo.setItemText(0, _translate("MainWindow", "HTTP"))
        self.shareTypeCombo.setItemText(1, _translate("MainWindow", "FTP"))
        self.sharePathLabel.setText(_translate("MainWindow", "分享路径："))
        self.shareFileLbael.setText(_translate("MainWindow", "选取文件/文件夹："))
        self.createShareButton.setText(_translate("MainWindow", "新建分享"))
        item = self.shareListTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.shareListTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.shareListTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.shareListTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.shareListTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.shareListTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "5"))
        item = self.shareListTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "6"))
        item = self.shareListTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "7"))
        item = self.shareListTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "8"))
        item = self.shareListTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "9"))
        item = self.shareListTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "10"))
        item = self.shareListTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "编号"))
        item = self.shareListTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "分享类型"))
        item = self.shareListTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "分享文件/文件夹路径"))
        item = self.shareListTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "浏览数量"))
        item = self.shareListTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "分享状态"))
        item = self.shareListTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "操作"))
        __sortingEnabled = self.shareListTable.isSortingEnabled()
        self.shareListTable.setSortingEnabled(False)
        self.shareListTable.setSortingEnabled(__sortingEnabled)
        self.shareLinkLabel.setText(_translate("MainWindow", "分享链接："))
        self.shareLinkButton.setText(_translate("MainWindow", "点击加载"))
        self.backupButton.setText(_translate("MainWindow", "返回上一级目录"))
        self.downloadDirButton.setText(_translate("MainWindow", "下载当前整个文件夹"))
        item = self.fileListTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.fileListTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.fileListTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.fileListTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件列表(文件点击下载,文件夹点击展开)"))
        self.removeDownloadsButton.setText(_translate("MainWindow", "清除下载记录"))
        item = self.downloadListTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件名"))
        item = self.downloadListTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "下载状态"))
        self.authorLabel.setText(_translate("MainWindow", "By: 大宝天天见丶"))
        self.versionLabel.setText(_translate("MainWindow", "v0.0.1"))