name: 🐛 报告错误
description: 报告一个错误（Bug），请先搜索 Issue 列表中有无你要提的问题。
title: "[Bug]: "
body:
- type: checkboxes
  id: check-answer
  attributes:
    label: 解决方案检查
    description: 请确保你已完成以下所有操作。
    options:
      - label: 我已搜索 [Issue 列表](https://github.com/zzmx-sudo/file_sharer-Desktop/issues?q=is%3Aissue+)，并没有发现类似的问题。
        required: true
- type: textarea
  id: bug_title
  attributes:
    label: 错误简述
    description: 简要描述你遇到的 Bug。
  validations:
    required: true
- type: textarea
  id: bug_description
  attributes:
    label: 错误详情
    description: 请详细描述遇到的问题，包括复现步骤。
    placeholder: "例如: 1. 打开应用\n2. 点击 '服务端'\n3. 点击'新建分享'\n4.发生崩溃"
  validations:
    required: true
- type: textarea
  id: expected_behavior
  attributes:
    label: 预期行为
    description: 你所期待的应用的行为是什么？
  validations:
    required: true
- type: textarea
  id: actual_behavior
  attributes:
    label: 实际行为
    description: 应用的实际表现是什么？
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: File_Sharer-Desktop 版本
    description: 你使用什么版本的 File_Sharer-Desktop？
    placeholder: 例如 0.3.1
  validations:
    required: true
- type: input
  id: last-known-working-version
  attributes:
    label: 最后正常的版本
    description: 如果有，请在此处填写最后正常的版本。
    placeholder: 例如 0.3.0
- type: input
  id: operating-system-version
  attributes:
    label: 操作系统版本
    description: |
      你使用什么版本的操作系统？
      在 macOS 上，单击「Apple 菜单 > 关于本机」；
      在 Windows 上，单击「开始按钮 > 设置 > 系统 > 关于」。
    placeholder: "例如 Windows 11 版本 24H2 或 macOS Sequoia 15.1.1"
  validations:
    required: true
- type: textarea
  id: additional-information
  attributes:
    label: 附加信息
    description: 如果你的问题需要进一步解释，或者你所遇到的问题不容易重现，请在此处添加更多信息。（直接把图片/视频拖到编辑框即可添加图片/视频）
