__all__ = ["RET", "MSG_MAP"]


class RET:
    OK = 200
    FORBIDDEN = 400
    FILENOTFOUND = 404
    SEVERERR = 500
    SIZEOFFOLDER = 3001
    CANNOTDOWNLOADFOLDER = 4001
    FTPDOWNLOADWITHOUTCLIENT = 4002
    REQUIREPWD = 4003
    UPLOADTONONFOLDER = 4004
    UPLOADFILEISEXISTS = 4005
    UPLOADCHUNKEXISTS = 4006
    MERGELOSSCHUNK = 4007
    FILETRANSFERERR = 5001
    FTPTYPEERR = 5002


MSG_MAP = {
    RET.OK: "OK",
    RET.FORBIDDEN: "For Bidden",
    RET.FILENOTFOUND: "错误的路径或文件已不存在",
    RET.SEVERERR: "发生未知错误",
    RET.SIZEOFFOLDER: "不能获取文件夹的大小",
    RET.CANNOTDOWNLOADFOLDER: "无法直接下载文件夹, 请使用客户端进行下载",
    RET.FTPDOWNLOADWITHOUTCLIENT: "ftp分享的文件/文件夹请使用客户端进行下载",
    RET.REQUIREPWD: "缺少密码验证",
    RET.UPLOADTONONFOLDER: "不能上传至非文件夹内",
    RET.UPLOADFILEISEXISTS: "已存在同名文件",
    RET.UPLOADCHUNKEXISTS: "已存在同名分片",
    RET.MERGELOSSCHUNK: "上传的分片不是完整的",
    RET.FILETRANSFERERR: "文件/文件夹对象没有被正确传递",
    RET.FTPTYPEERR: "非预期的分享类型",
}
