on:
  push:
    branches:
      - develop

jobs:
  Windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.*'
          cache: 'pip'

      - name: Install Dependencies with pip
        run: pip install -r requirements.txt

      - name: Compress windows Binary
        run: |
          cd .\scripts
          echo %cd% && dir
          python modify_script_file.py
          .\build_windows_x64.bat

      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.1.0"
          prerelease: false
          title: "Release v0.1.0"
          files: |
            build\installer\*.7z
            build\installer\*.exe

  MacOs:
    name: Macos
    runs-on: macos-latest
    steps:
      - name: Clone code
        uses: actions/ckeckout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.*'
          cache: 'pip'

      - name: Install Dependencies with pip
        run: pip install -r requirements.txt

      - name: Compress Macos Binary
        run: |
          cd ./scripts
          python modify_script_file.py
          sh build_mac.sh

      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.1.0"
          prerelease: false
          title: "Release v0.1.0"
          files: |
            build\installer\*.dmg
