on:
  push:
    branches:
      - Rel_*

jobs:
  Windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.*'
          cache: 'pip'

      - name: Install Dependencies with pip
        run: pip install -r requirements.txt

      - name: Install 7z & NSIS

  MacOs:
    name: Macos
    runs-on: macos-latest
    steps:
      - name: Clone code
        uses: actions/ckecout@v3

      - name: Install Python
        uses: actioons/setip-python@v4
        with:
          python-version: '3.8.*'
          cache: 'pip'

      - name: Install Dependencies with pip
        run: pip install -r requirements.txt

      - name: Install create-dmg
